include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = VCamApp

VCamApp_FILES = main.m VCamAppDelegate.m VCamRootViewController.m ../VCamOverlay/VCamSettings.m
VCamApp_FRAMEWORKS = UIKit CoreGraphics
VCamApp_CFLAGS = -fobjc-arc -I../VCamOverlay

include $(THEOS_MAKE_PATH)/application.mk
